backbone: "efficientnet-b3"
encoder_weights: "imagenet"
seed: 1997
num_train_epochs: 1000
max_train_steps: 10000
valid_delta_steps: 100
checkpointing_steps: 1000
gradient_accumulation_steps: 1
max_grad_norm: 1.0
mixed_precision: "no"
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.0e-2
adam_epsilon: 1.0e-8
learning_rate: 2.0e-4
scale_lr: false 
lr_scheduler: "cosine"
lr_warmup_steps: 500
train_batch_size: 32
valid_batch_size: 32
num_workers: 8
output_dir: "../models"
wandb_project_name: "contrails"