seed: 1997
train_batch_size: 32
valid_batch_size: 8
num_workers: 8
output_dir: "../models/checkpoints"
wandb_project: "contrails-diffusion"

early_stopping:
  mode: "min"
  patience: 100
  verbose: 1

accumulate:
  scheduling: {0: 8, 8: 4, 12: 2, 16: 1}

swa:
  swa_lrs: 1.0e-2
  swa_epoch_start: 0.6

model:
  scheduler:
    name: "cosine_with_hard_restarts_schedule_with_warmup"
    params:
      num_warmup_steps: 500
      num_training_steps: 20000
      num_cycles: 1
  optimizer:
    learning_rate: 2.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.0
    adam_epsilon: 1.0e-8
    num_cycles: 1
  cond_drop_rate: 0.1
  arch_config: "../configs/diffusion/arch.yaml"
  train_cond_stage: True
  train_logvar: True
  inference_steps: 200
  eta: 1.0
  guidance_scale: 1.2

trainer:
  min_steps: 20000
  max_steps: 20000
  max_epochs: 1000
  gradient_clip_val: 1.0
  enable_progress_bar: false
  precision: 32
  accelerator: "gpu"
  devices: 2
  strategy: "ddp_find_unused_parameters_false"

synthesize:
  num_synthetic: 5000
  inference_steps: 500
  guidance_scale: 1.2
  eta: 1.0
  device: "cuda"
  batch_size: 32
  output_dir: "../data/synthetic"
  append: false # Set to true to add to existing synthetic images

