seed: 1997
train_batch_size: 16
valid_batch_size: 64
num_workers: 8
output_dir: "../models/checkpoints"
pseudo_labels_dir: "../data/pseudo-labels/predictions"
wandb_project: "contrails-pretraining"

early_stopping:
  mode: "min"
  patience: 100
  verbose: 1

accumulate:
  scheduling: {0: 16, 8: 8, 12: 4, 16: 2}

swa:
  swa_lrs: 1.0e-2
  swa_epoch_start: 0.6

model:
  scheduler:
    name: "cosine_with_hard_restarts_schedule_with_warmup"
    params:
      num_warmup_steps: 500
      num_training_steps: 10000
      num_cycles: 1
  optimizer:
    learning_rate: 4.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.0
    adam_epsilon: 1.0e-8
    num_cycles: 1
  encoder: "convnextv2_base.fcmae_ft_in22k_in1k_384"
  decoder_channels: [512, 256, 128, 64, 32]
  decoder_attention: "scse"
  label_smoothing: 0.0
  num_synthetic: 0
  image_size: 384

trainer:
  min_steps: 10000
  max_steps: 10000
  max_epochs: 1000
  gradient_clip_val: 1.0
  enable_progress_bar: false
  precision: "16-mixed"
  accelerator: "gpu"
  devices: 2
  strategy: "ddp_find_unused_parameters_true"

evaluation:
  device: "cuda"
  bins: 100
  min_size: 10
  output_dir: "../data/pseudo-labels"